#!/usr/bin/env bash
# Ensure a project-local JDK 25 home whose bin/java always injects the JDK 25
# opt-in flags. Gradle Worker Daemons invoke the daemon's java executable by
# absolute path and do NOT inherit org.gradle.jvmargs / JAVA_TOOL_OPTIONS, so
# ktlint's process-isolated workers would otherwise spam JEP 498 Unsafe
# warnings from kotlin-compiler-embeddable 2.2.x.
#
# Usage:  source scripts/ensure-jdk25-home.sh
# Effect: exports JAVA_HOME (and prepends it to PATH) pointing at the wrapper.
set -euo pipefail

# Use private names so sourcing from build.sh does not clobber SCRIPT_DIR.
_ENSURE_JDK25_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
_ENSURE_JDK25_REPO_ROOT="$(cd "$_ENSURE_JDK25_SCRIPT_DIR/.." && pwd)"
WRAPPER_ROOT="$_ENSURE_JDK25_REPO_ROOT/.jdk25-home"

resolve_real_jdk() {
    if [[ -n "${ANDROID_APP_REAL_JAVA_HOME:-}" && -x "${ANDROID_APP_REAL_JAVA_HOME}/bin/java" ]]; then
        echo "$ANDROID_APP_REAL_JAVA_HOME"
        return
    fi
    # Prefer an already-selected real JDK 25 (CI setup-java, user JAVA_HOME),
    # but never recurse into our own wrapper.
    if [[ -n "${JAVA_HOME:-}" \
        && -x "${JAVA_HOME}/bin/java" \
        && "${JAVA_HOME}" != "${WRAPPER_ROOT}" ]]; then
        ver="$("${JAVA_HOME}/bin/java" -version 2>&1 | head -1 || true)"
        if [[ "$ver" == *'"25'* || "$ver" == *' 25.'* ]]; then
            echo "$JAVA_HOME"
            return
        fi
    fi
    local candidate
    for candidate in \
        /usr/lib/jvm/java-25-openjdk-amd64 \
        /usr/lib/jvm/java-25-openjdk \
        "$HOME/.jdks/jdk-25"; do
        if [[ -x "$candidate/bin/java" ]]; then
            echo "$candidate"
            return
        fi
    done
    echo "ensure-jdk25-home: no JDK 25 installation found" >&2
    return 1
}

REAL_JDK="$(resolve_real_jdk)"

# Rebuild the wrapper tree when the real JDK path changes or java is missing.
MARKER="$WRAPPER_ROOT/.real-jdk"
if [[ ! -x "$WRAPPER_ROOT/bin/java" ]] \
    || [[ ! -f "$MARKER" ]] \
    || [[ "$(cat "$MARKER" 2>/dev/null || true)" != "$REAL_JDK" ]]; then
    rm -rf "$WRAPPER_ROOT"
    mkdir -p "$WRAPPER_ROOT/bin"
    local_item=
    for local_item in "$REAL_JDK"/*; do
        base="$(basename "$local_item")"
        [[ "$base" == "bin" ]] && continue
        ln -s "$local_item" "$WRAPPER_ROOT/$base"
    done
    for local_item in "$REAL_JDK/bin"/*; do
        base="$(basename "$local_item")"
        [[ "$base" == "java" ]] && continue
        ln -s "$local_item" "$WRAPPER_ROOT/bin/$base"
    done
    cat > "$WRAPPER_ROOT/bin/java" << EOF
#!/usr/bin/env bash
# Auto-generated by scripts/ensure-jdk25-home.sh - do not edit.
exec "$REAL_JDK/bin/java" \\
  --sun-misc-unsafe-memory-access=allow \\
  --enable-native-access=ALL-UNNAMED \\
  "\$@"
EOF
    chmod +x "$WRAPPER_ROOT/bin/java"
    echo "$REAL_JDK" > "$MARKER"
fi

export ANDROID_APP_REAL_JAVA_HOME="$REAL_JDK"
export JAVA_HOME="$WRAPPER_ROOT"
export PATH="$JAVA_HOME/bin:$PATH"
unset _ENSURE_JDK25_SCRIPT_DIR _ENSURE_JDK25_REPO_ROOT
